import sqlite3
import json

# Nome do arquivo JSON dos produtos
dados_produtos  = [
    {
        "id": 1,
        "nome": 'Laramora',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '',
        "alerta": '--',
        "composicao": ['Suco de Laranja',
                     'Suco de Morango'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/suco-laramora-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 2,
        "nome": 'Limãomora',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '',
        "alerta": '--',
        "composicao": ['Suco de Limão',
                     'Suco de Morango'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Limamora.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 3,
        "nome": 'Maramora',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '',
        "alerta": '--',
        "composicao": ['Suco de Maracuja',
                     'Suco de Morango'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Maramora-2.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 4,
        "nome": 'Del Valle Uva',
        "grupo": 'bebida não alcoolica',
        "liquido": '300ml',
        "obs": '',
        "alerta": '--',
        "composicao": ['Suco Del Valle'
                     ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/858764/nectar_del_valle_lata_290ml_uva_c_06_293_1_2f7b5c2501770ffed986efd74c7a4466.jpeg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 11,
        "nome": 'Pink Lemonade',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": 'Vegetariano',
        "alerta": 'Este produto contém ovo, logo não deve ser sugerido para pessoas veganas.',
        "composicao": ['Lemonade Base (Base da limonada)',
                     'Xarope Pimenta rosa',
                     'Xarope de Grenadine',
                     'Pimenta rosa',
                     '1 Fatia de Limão'], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7660-min-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "true",
        "vegano": "false",
    }, {
        "id": 12,
        "nome": 'Pink Lemonade',
        "grupo": 'bebida não alcoolica',
        "liquido": '600ml',
        "obs": 'Vegetariano',
        "alerta": 'Este produto contém ovo, logo não deve ser sugerido para pessoas veganas.',
        "composicao": ['Lemonade Base (Base da limonada)',
                     'Xarope Pimenta rosa',
                     'Xarope de Grenadine',
                     'Pimenta rosa',
                     '2 Fatias de Limão'], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7660-min-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "true",
        "vegano": "false",
    }, {
        "id": 13,
        "nome": 'Suco Maracuja',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '--',
        "alerta": 'Este suco não leva açucar normalmente',
        "composicao": ['Maracuja Fruta'], "sabores": [],
        "imagem": 'https://nutripao.com/wp-content/uploads/2022/08/Suco-de-Maracuja-500ml.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 14,
        "nome": 'Suco Morango',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '--',
        "alerta": 'Este suco é naturalmente adoçado.',
        "composicao": ['Poupa de Morango'], "sabores": [],
        "imagem": 'https://anamariabrogui.com.br/assets/uploads/receitas/fotos/usuario-1919-b1f4302be3cedb38d40dfc19b7146bbc.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 15,
        "nome": 'Suco Limão',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '--',
        "alerta": 'Este suco não leva açucar normalmente.',
        "composicao": ['limão fruta'], "sabores": [],
        "imagem": 'https://img.freepik.com/fotos-premium/suco-de-limao-verde-em-um-copo-com-frutas-sobre-a-mesa-de-madeira_92534-1703.jpg?w=2000',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 16,
        "nome": 'Limonada Suiça',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": 'Batido no liquidificador',
        "alerta": 'Este suco não leva açucar normalmente.',
        "composicao": ['limão fruta'], "sabores": [],
        "imagem": 'https://img.freepik.com/fotos-premium/suco-de-limao-verde-em-um-copo-com-frutas-sobre-a-mesa-de-madeira_92534-1703.jpg?w=2000',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 17,
        "nome": 'Limonada Suiça Especial',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": 'Batido no liquidificador',
        "alerta": 'Este suco não leva açucar normalmente.',
        "composicao": ['limão fruta', 'leite condensado', 'leite integral'], "sabores": [],
        "imagem": 'https://www.acasaencantada.com.br/wp-content/uploads/2022/03/Limonada-suica-de-leite-condensado.webp',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 18,
        "nome": 'Suco Abacaxi',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '--',
        "alerta": 'Este suco é naturalmente adoçado.',
        "composicao": ['Poupa de Abacaxi'], "sabores": [],
        "imagem": 'https://i.ytimg.com/vi/mcbCHc3Mq3w/maxresdefault.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 19,
        "nome": 'Suco de Tomate',
        "grupo": 'bebida não alcoolica',
        "liquido": '340ml',
        "obs": '--',
        "alerta": 'Este suco é naturalmente adoçado.',
        "composicao": ['Suco de Tomate',
                     'Pimenta Preta',
                     'Molho Ingles'], "sabores": [],
        "imagem": 'https://p2.trrsf.com/image/fget/cf/1200/900/middle/images.terra.com/2023/03/19/169488901-suco-de-tomate.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 50,
        "nome": 'Ice Tea Tradicional',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Chá preto',
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Flavored-Teas-Trio-Mug-cmyk_tif_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 51,
        "nome": 'Ice Tea Pessego',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Chá preto',
                     'xarope de pessego'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Flavored-Teas-Trio-Mug-cmyk_tif_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 52,
        "nome": 'Ice Tea Cranberry',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Chá preto',
                     'xarope de Cranberry'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Flavored-Teas-Trio-Mug-cmyk_tif_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 53,
        "nome": 'Ice Tea Limão',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Chá preto',
                     'xarope de limão'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Flavored-Teas-Trio-Mug-cmyk_tif_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 60,
        "nome": 'Coca-Cola',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Refrigerante'
                     ], "sabores": [],
        "imagem": 'https://meuprimeirobatomvermelho.files.wordpress.com/2017/09/img_20170918_135800671.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 61,
        "nome": 'Coca-Cola Zero',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Refrigerante'
                     ], "sabores": [],
        "imagem": 'https://meuprimeirobatomvermelho.files.wordpress.com/2017/09/img_20170918_135800671.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 62,
        "nome": 'Fanta-Laranja',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Refrigerante'
                     ], "sabores": [],
        "imagem": 'https://img.cybercook.com.br/imagens/receitas/631/refrigerante-de-laranja-caseiro.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 63,
        "nome": 'Sprite Zero',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Refrigerante'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 64,
        "nome": 'Guarana Antartica',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Refrigerante'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 65,
        "nome": 'Guarana Antartica Zero',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": 'Refil',
        "alerta": '',
        "composicao": ['Refrigerante'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 70,
        "nome": 'Café  Leggero',
        "grupo": 'bebida não alcoolica',
        "liquido": '',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Outback-Cafe%E2%95%A0%C3%BC-com-Chocolate_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 71,
        "nome": 'Café  Ristretto',
        "grupo": 'bebida não alcoolica',
        "liquido": '',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Outback-Cafe%E2%95%A0%C3%BC-com-Chocolate_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 72,
        "nome": 'Café  Descafeinado',
        "grupo": 'bebida não alcoolica',
        "liquido": '',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Outback-Cafe%E2%95%A0%C3%BC-com-Chocolate_305x342-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 80,
        "nome": 'Agua sem Gás',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://www.aguamineralcrystal.com.br/static/a7c01828c1f74d28830a2cee22a80002/f2cbb/garrafas-agua-crystal.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 81,
        "nome": 'Agua com Gás',
        "grupo": 'bebida não alcoolica',
        "liquido": '500ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://www.aguamineralcrystal.com.br/static/a7c01828c1f74d28830a2cee22a80002/f2cbb/garrafas-agua-crystal.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 90,
        "nome": 'Chopp Brahma',
        "grupo": 'bebida alcoolica',
        "liquido": '340ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/AF_61.4299.3361.5880_51638_EXP_Imagem-Chopp_CHOPP_225X255px-2.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 92,
        "nome": 'Chopp Brahma',
        "grupo": 'bebida alcoolica',
        "liquido": '600ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/AF_61.4299.3361.5880_51638_EXP_Imagem-Chopp_CHOPP_225X255px-2.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 93,
        "nome": 'Chopp Brahma Escuro*',
        "grupo": 'bebida alcoolica',
        "liquido": '340ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://media-cdn.tripadvisor.com/media/photo-p/0a/aa/d8/53/chopp-escuro-bem-gelado.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 94,
        "nome": 'Chopp Brahma Escuro*',
        "grupo": 'bebida alcoolica',
        "liquido": '600ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://media-cdn.tripadvisor.com/media/photo-p/0a/aa/d8/53/chopp-escuro-bem-gelado.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 95,
        "nome": 'Chopp Colorado Appia*',
        "grupo": 'bebida alcoolica',
        "liquido": '350ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/chopp-appia-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 96,
        "nome": 'Chopp Colorado Appia*',
        "grupo": 'bebida alcoolica',
        "liquido": '600ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/chopp-appia-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 100,
        "nome": 'Goose Island Midway',
        "grupo": 'bebida alcoolica',
        "liquido": '355ml',
        "obs": 'Estilo: Session IPA A Goose Island Midway IPA é uma Session IPA leve e refrescante, com aroma de frutas tropicais. *Sujeito a disponibilidade.',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Goose-Midway.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 102,
        "nome": "Beck's",
        "grupo": 'bebida alcoolica',
        "liquido": '330ml',
        "obs": '',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Becks.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 103,
        "nome": 'Colorado Ribeirão Lager',
        "grupo": 'bebida alcoolica',
        "liquido": '330ml',
        "obs": 'Estilo: American lager Uma lager leve e refrescante com toque de laranja.',
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/ribeir%C3%A3o_lager_300ml-min-225x255.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 104,
        "nome": 'Brahma 0,0% Long Neck',
        "grupo": 'bebida não alcoolica',
        "liquido": '330ml',
        "obs": 'Estilo: Pilsen',
        "alerta": 'Mesmo esta bebida não sendo alcoolica, não deve ser sugerida para menores.',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Brahma-0-alcool.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 110,
        "nome": 'Jack Trio',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "Do Tennessee para sua mesa em dose tripla, esse é o trio de drinks para os amantes de Jack Daniel’s. O primeiro, uma combinação do tradicional Jack Daniel's Old No.7 com limonada, xaropes de baunilha, de pimenta rosa e de grenadine, finalizado com pimenta rosa em grãos. O segundo, feito com Jack Fire, limonada, xaropes de baunilha e de gengibre, finalizado com espuma de gengibre e crumbles *contém glúten e lactose. E o terceiro, feito com Jack Honey, limonada, polpa de maracujá e xaropes de maracujá vermelho e de pimenta rosa.",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Jack-trio.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 111,
        "nome": 'Moscow Mule Outback',
        "grupo": 'bebida alcoolica',
        "liquido": '340ml',
        "obs": "Releitura Aussie do tradicional Moscow Mule, preparado com vodka e suco de limão. Finalizado com espuma de xarope de gengibre e, para deixar o clima mais gostoso, servido em nossa caneca congelada.",
        "alerta": '',
        "composicao": ['suco de limão adoçado', 'vodka importada', 'espuma de gengibre', '1 fatia de limão'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Moscow-Mule.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 112,
        "nome": 'Gold Coast Rita',
        "grupo": 'bebida alcoolica',
        "liquido": '340ml',
        "obs": "Um dos drinks mais pedidos da casa, nossa refrescante margarita frozen é preparada com tequila nobre do México, licor triple sec e ingredientes exclusivos do Outback.",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Gold-Coast-Rita-1.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 113,
        "nome": 'Strawberry Rita',
        "grupo": 'bebida alcoolica',
        "liquido": '340ml',
        "obs": "Extremamente refrescante, esta versão da nossa Gold Coast Rita® é batida com morangos.",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Strawberry-Rita-1.png',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 114,
        "nome": 'Beer Mule',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "O seu chopp em uma versão totalmente inédita, com muita identidade Outback! A combinação de Jack daniel's gengibre, chopp e toque de limão.",
        "alerta": '',
        "composicao": ['suco de limão sem açucar', 'xarope de gengibre', 'jack daniels tennessee', 'espuma de choppe'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7681-min-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 115,
        "nome": 'Margarita Trio',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "Trio de margaritas ideal pra compartilhar com seus mates. Escolha três sabores entre: Tradicional, Strawberry, Cranberry, Rock Melon e Curaçau Blue.",
        "alerta": '',
        "composicao": [
        ],
        "sabores": ['original', 'blue', 'rock melon', 'strawberry', 'cranberry'
                  ],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/Margarita-Trio-V2-cmyk-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 116,
        "nome": 'Brazilian Beach Cocktail',
        "grupo": 'bebida alcoolica',
        "liquido": '340ml',
        "obs": "Saborosa mistura de kiwis e morangos, batidos com essência de cranberry e vodka. Inspirado nas famosas praias brasileiras.",
        "alerta": '',
        "composicao": ['morango',
                     'kiwi',
                     'vodka importada',
                     'xarope de morango',
                     'xarope de cranberry'
                     ], "sabores": [],
        "imagem": 'https://media-cdn.tripadvisor.com/media/photo-s/0b/5f/1d/17/brazilian-beach.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 120,
        "nome": 'Mango G&T',
        "grupo": 'bebida alcoolica',
        "liquido": '500ml',
        "obs": "A combinação perfeita entre o Gin Tanqueray London Dry e notas de manga, mel e canela.",
        "alerta": '',
        "composicao": ['agua tônica', 'tanqueray London', 'xarope de mel', 'xarioe de manga', '1 canela em pau', '1 fatia laranja', 'gelo'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7481-min-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 121,
        "nome": 'Passion G&T',
        "grupo": 'bebida alcoolica',
        "liquido": '500ml',
        "obs": "Toda refrescância de um G&T e o toque refrescante do maracujá vermelho.",
        "alerta": '',
        "composicao": ['agua tônica', 'tanqueray London', 'polpa maracuja', 'xarope de maracuja vermelho', '1 fatia de laranja', 'gelo'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7470-min-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 122,
        "nome": 'Sevilla & Tonic',
        "grupo": 'bebida alcoolica',
        "liquido": '500ml',
        "obs": "Toda resfrescância de um G&T tradicional com um toque de laranja-de-sevilha.",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7463-min-1-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 123,
        "nome": 'Tanqueray & Tonic',
        "grupo": 'bebida alcoolica',
        "liquido": '500ml',
        "obs": "O clássico G&T com toque de limão pra refrescar seu momento Outback.",
        "alerta": '',
        "composicao": ['agua tônica', 'tanqueray London', 'gelo'
                     ], "sabores": [],
        "imagem": 'https://s3.amazonaws.com/institucional-statics-files/site/uploads/03A7454-min-225x255.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 130,
        "nome": 'Vodka Nacional',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://bebidasdomundo.com/wp-content/uploads/2020/10/orloff998.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 131,
        "nome": 'Vodka Importada',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://cdn.spiritshop.com.br/adegaportofino/image/cache/data/up_system/product-51607/keteleonee-1500x1500.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 132,
        "nome": 'Cachaça Premium',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/686651/cachaca_leblon_750ml_13543257_1_20190308181247.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 133,
        "nome": 'Tequila',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/584235/tequila_el_jimador_ouro_750ml_438983660_1_25beb02abfed10a83e50e3e15d391f53.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 134,
        "nome": 'Saquê',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/686651/sake_azuma_kirin_soft_740ml_saque_33032030_1_366f72ac85d52d76da9b82498becfb7b.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 135,
        "nome": 'Licor 43',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://www.beale.com.br/uploads/1604769790.jpeg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 136,
        "nome": 'Licor Amarula',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://www.varanda.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/i/licor-amarula-cream-375ml-6001495062478.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 140,
        "nome": 'Whisky buchanans',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/686651/buchanan_s_deluxe_12_anos_blended_scotch_whisky_750ml_35990827_1_d8ded53848e1efae069da14f6047c679.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 141,
        "nome": 'Whisky chivas',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/1014792/chivas_regal_whisky_12_anos_escoces_750ml_24363_1_9e6084b432b2a3fcc62d456a86c4f993.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 142,
        "nome": 'Jack Daniels Tennessee',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/686651/whiskey_jack_daniel_s_1l_13498087_1_20190308181636.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 143,
        "nome": 'Jack Daniels honey',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images-americanas.b2w.io/produtos/123108370/imagens/whisky-jack-daniel-s-honey-mel-1-litro/123108388_1_large.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 144,
        "nome": 'Jack Daniels fire',
        "grupo": 'bebida alcoolica',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://images.tcdn.com.br/img/img_prod/686651/jack_daniel_s_fire_licor_de_whiskey_e_canela_1l_28297521_1_9e2fe6869e41b8b5d0563603bb2c5dbb.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 150,
        "nome": 'Maracuja ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Maracuj%C3%A1_em_fundo_preto_%282%29.JPG/800px-Maracuj%C3%A1_em_fundo_preto_%282%29.JPG',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 151,
        "nome": 'Morango ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://conteudo.imguol.com.br/c/entretenimento/78/2018/02/28/morango-1519823853148_v2_4x3.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 152,
        "nome": 'Kiwi ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://www.sindafep.org.br/media/img_noticias/fresh-kiwi-cut-into-half-put-on-wooden-cutting-board.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 153,
        "nome": 'Lichia ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://www.quitandatomio.com.br/upload/14-beneficios-da-lichia-para-que-serve-e-propriedades.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 154,
        "nome": 'Amora ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://p2.trrsf.com/image/fget/cf/1200/675/middle/images.terra.com/2022/10/17/1173549954-beneficio-da-amora.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 155,
        "nome": 'Framboesa ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": [
        ], "sabores": [],
        "imagem": 'https://conteudo.imguol.com.br/c/entretenimento/b5/2022/03/03/framboesa-1646327024224_v2_1254x836.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 156,
        "nome": 'Citrus',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Tangerina', 'Lima', 'Limão', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 157,
        "nome": 'Dreams',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Morango', 'Maracuja', 'Limão', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 158,
        "nome": 'Frutas Vermelhas',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Morango', 'Framboesa', 'Amora', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 160,
        "nome": 'Lima-Pimenta ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['lima', 'pimenta rosa', 'destilado', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 161,
        "nome": 'Strawberry Ginger ',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['limão', 'gengibre', 'xarope de morango', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 162,
        "nome": 'Rock Melon',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['limão', 'melão cantaloupe', 'xarope de melão', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 163,
        "nome": 'Red Passion',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Maracujá', 'Limão', 'xarope de maracuja vermelho', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 170,
        "nome": 'Dry Martini',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['GIN', 'Martini Dry', 'xarope de maracuja vermelho', 'fatia da casca do limão', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 171,
        "nome": 'Bloody Mary',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Suco de Tomate temperado', 'Vodka Nacional', 'Aipo', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    },
    {
        "id": 172,
        "nome": 'Hi-Fi',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Refrigerante de laranja', 'Vodka Nacional', 'gelo'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 173,
        "nome": 'Rita T / Margarita',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Tequila', 'Licor de Pessego', 'Suco de limão', 'taça com borda de sal'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 174,
        "nome": 'Kir',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['vinho branco', 'licor de cassis', 'und Amora'
                     ], "sabores": [],
        "imagem": 'https://cdn.diffords.com/contrib/stock-images/2018/05/5af308c5c07ff.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 175,
        "nome": 'Kir Royal',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Espumante', 'Licor de cassis', 'und Amora'
                     ], "sabores": [],
        "imagem": 'https://cdn.diffords.com/contrib/stock-images/2018/05/5af308c5c07ff.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 176,
        "nome": 'Pina Colada',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Polpa de Abacaxi', 'Bacardi', 'Leite de Coco', 'Leite Condensado'
                     ], "sabores": [],
        "imagem": 'https://media-cdn.tripadvisor.com/media/photo-s/0b/b8/62/d1/pinacolada.jpg',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 177,
        "nome": 'Black Russian',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Vodka', 'Licor de café'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }, {
        "id": 178,
        "nome": 'Jack Cola',
        "grupo": '',
        "liquido": '',
        "obs": "",
        "alerta": '',
        "composicao": ['Jack Daniels', 'Coca-Cola'
                     ], "sabores": [],
        "imagem": '',
        "alcolico": "false",
        "vegetariano": "false",
        "vegano": "false",
    }

]

# Nome do arquivo do banco de dados SQLite
db_file = 'produtos.db'

def create_database():
    # Cria uma conexão com o banco de dados
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()

    # Cria a tabela para armazenar os produtos
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS produtos (
            id INTEGER PRIMARY KEY,
            nome TEXT,
            grupo TEXT,
            liquido TEXT,
            obs TEXT,
            alerta TEXT,
            composicao TEXT,
            sabores TEXT,
            imagem TEXT,
            alcoolico TEXT,
            vegetariano TEXT,
            vegano TEXT
        )
    ''')

    # Insere os dados dos produtos na tabela
    for produto in dados_produtos:
        cursor.execute('''
            INSERT INTO produtos (
                id, nome, grupo, liquido, obs, alerta, composicao, sabores,
                imagem, alcoolico, vegetariano, vegano
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            produto['id'],
            produto['nome'],
            produto['grupo'],
            produto['liquido'],
            produto['obs'],
            produto['alerta'],
            json.dumps(produto['composicao']),
            json.dumps(produto['sabores']),
            produto['imagem'],
            produto['alcolico'],
            produto['vegetariano'],
            produto['vegano']
        ))

    # Salva as alterações e fecha a conexão com o banco de dados
    conn.commit()
    conn.close()

if __name__ == '__main__':
    create_database()
    print('Banco de dados criado e dados importados com sucesso!')